- name: Copy pf configuration (nat)
  template:
    backup: '{{ jail_backup_old_files }}'
    src: 'pf.anchor.nat-jail.conf.j2'
    dest: '/etc/pf.anchor.nat-jail.{{ jail_name }}-jailed.conf'
  notify:
    - Reload pf

- name: Add pf configuration to anchor.nat-jail conf
  lineinfile:
    backup: '{{ jail_backup_old_files }}'
    dest: '/etc/pf.anchor.nat-jail.conf'
    state: present
    line: 'include "/etc/pf.anchor.nat-jail.{{ jail_name }}-jailed.conf"'
  notify:
    - Reload pf

- name: Copy pf configuration (rls)
  template:
    backup: '{{ jail_backup_old_files }}'
    src: 'pf.anchor.rls-jail.conf.j2'
    dest: '/etc/pf.anchor.rls-jail.{{ jail_name }}-jailed.conf'
  notify:
    - Reload pf

- name: Add pf configuration to anchor.rls-jail conf
  lineinfile:
    backup: '{{ jail_backup_old_files }}'
    dest: '/etc/pf.anchor.rls-jail.conf'
    line: 'include "/etc/pf.anchor.rls-jail.{{ jail_name }}-jailed.conf"'
    state: present
  notify:
    - Reload pf
