---
- name: Make sure old pf configuration file for nat is gone
  file:
    path: /etc/pf.anchor.nat-jail.{{ jail_name }}-dns.conf
    state: absent
  notify:
    - Reload pf

- name: Remove old pf configuration file from configuration
  lineinfile:
    dest: /etc/pf.anchor.nat-jail.conf
    state: absent
    line: 'include "/etc/pf.anchor.nat-jail.{{ jail_name }}-dns.conf"'
  notify:
    - Reload pf

- name: Copy pf configuration (nat)
  template:
    src: pf.anchor.nat-jail.conf.j2
    dest: /etc/pf.anchor.nat-jail.{{ jail_name }}-jailed.conf
  notify:
    - Reload pf

- name: Add pf configuration to anchor.nat-jail conf
  lineinfile:
    dest: /etc/pf.anchor.nat-jail.conf
    state: present
    line: 'include "/etc/pf.anchor.nat-jail.{{ jail_name }}-jailed.conf"'
  notify:
    - Reload pf

- name: Copy pf configuration (rls)
  template:
    src: pf.anchor.rls-jail.conf.j2
    dest: /etc/pf.anchor.rls-jail.{{ jail_name }}-jailed.conf
  notify:
    - Reload pf

- name: Add pf configuration to anchor.rls-jail conf
  lineinfile:
    dest: /etc/pf.anchor.rls-jail.conf
    state: present
    line: 'include "/etc/pf.anchor.rls-jail.{{ jail_name }}-jailed.conf"'
  notify:
    - Reload pf
