- name: Install ssmtp for easy mail forwarding
  pkgng:
    name: 'ssmtp'
    state: present
    chroot: '{{ jail_home.stdout }}'
  register: pkg_result
  until: pkg_result is succeeded

- name: Copy ssmtp.conf into place
  template:
    backup: '{{ jail_backup_old_files }}'
    src: 'ssmtp.conf.j2'
    dest: '{{ jail_home.stdout }}/usr/local/etc/ssmtp/ssmtp.conf'

- name: Copy mailer configuration into place
  copy:
    backup: '{{ jail_backup_old_files }}'
    src: 'mailer.conf'
    dest: '{{ jail_home.stdout }}/etc/mail/mailer.conf'
