- name: Configure syslog
  lineinfile:
    backup: '{{ jail_backup_old_files }}'
    dest: '{{ jail_home.stdout }}/etc/syslog.conf'
    state: present
    line: '*.*      @{{ jail_syslogd_server }}'
    insertafter: '^#\s+Consult the syslog.conf'
  notify:
    - Reload {{ jail_name }} syslogd

- name: Enable remote syslog logging
  lineinfile:
    backup: '{{ jail_backup_old_files }}'
    dest: '{{ jail_home.stdout }}/etc/rc.conf'
    regexp: 'syslogd_flags='
    line: 'syslogd_flags="-c -s"'
  notify:
    - Reload {{ jail_name }} syslogd
